server:
  host: localhost
  port: '9001'
database:
  postgres:
    host: localhost
    username: postgres
    password: Dilshod@2005
    port: 5432
    name: postgres
filter:
  artist: ''
  title: ''
  price: 0